# @package _global_
input_data_path: "data/heart.csv"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop: []
input_model_path: "models/model.pkl"
output_predictions_path: "models/predictions.csv"