# @package _global_
input_data_path: "data/heart.csv"
metric_path: "models/metrics.json"
output_model_path: "models/model.pkl"
splitting_params:
  val_size: 0.2
  random_state: 3
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop: []
  target_col: "target"
train_params:
  model_type: "LogisticRegression"
  solver: "liblinear"